### ISSUE TITLE
Package API wrapper

### ISSUE THREAD

**Issue by theavege** [Al-Muhandis/fp-geonames#1]
Could you please make package with your API wrappers for Lazarus?

**Comment by Al-Muhandis** [comment]
> Could you please make package with your API wrappers for Lazarus?

Yes, I can. Will do

**Comment by Al-Muhandis** [comment]
Done [package](https://github.com/Al-Muhandis/fp-geonames/commit/2902049e71c5dbf97590c4b4a0320856551198b5)

**Comment by theavege** [comment]
@Al-Muhandis I apologized, but I want to suggest make a package with all your API wrappers
-  [CurrencyRates](https://github.com/Al-Muhandis/CurrencyRates)
- [fp-ton](https://github.com/Al-Muhandis/fp-ton)
- [CloudFlare](https://github.com/Al-Muhandis/CloudFlare)
- [Quran](https://github.com/Al-Muhandis/Quran.com.pascal)

**Comment by Al-Muhandis** [comment]
Hm... Then I didn't understand the request. And what should it look like? One package that contains all these APIs? And what is it for?

**Comment by theavege** [comment]
The idea is that these are API wrappers for pascal.

**Comment by Al-Muhandis** [comment]
There can be a lot of such API wrappers, why put them in one dependency? Maybe it's more correct to create some kind of list of API wrappers in Pascal? Like such awesome lists here on GitHub?

**Comment by theavege** [comment]
> Maybe it's more correct to create some kind of list of API wrappers in Pascal? Like such awesome lists here on GitHub?

It's very good idea!

**Comment by Al-Muhandis** [comment]
Let's create it. Should I do it or should you do it yourself?

**Comment by theavege** [comment]
Could you please do it?

**Comment by Al-Muhandis** [comment]
Yes, I can. Will do

**Comment by Al-Muhandis** [comment]
Is that what you suggested? https://github.com/Al-Muhandis/fpc-wrappers I made you a contributor right away
